version: '3.6'

services:
  chatbot:
    container_name: chatbot
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-configdb:/data/configdb
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - mongodb-configdb:/data/configdb
      - mongodb-data:/data/db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}

volumes:
  mongodb-data:
    name: chatui-mongodb-data
  mongodb-configdb:
    name: chatui-mongodb-configdb
